### ISSUE TITLE
getting issue while working with pyinstaller with django-fabric

### ISSUE THREAD

**Issue by mitulshah44** [mocco/django-fabric#26]
When I am directly run with fabric without pyinstaller, it works but when I created executable file, getting below error where fabfile is executable file.

```
fab -f ./fabfile runserver

Fatal error: Couldn't find any fabfiles!

Remember that -f can be used to specify fabfile path, and use -h for help.

Aborting.
```

Apart from this if I am running directly with manage.py, getting securty_key error

```
python manage.py runserver localhost:8000
Traceback (most recent call last):
  File "manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/env/lib/python2.7/site-packages/django/core/management/base.py", line 317, in run_from_argv
    connections.close_all()
  File "/home/ubuntu/env/lib/python2.7/site-packages/django/db/utils.py", line 229, in close_all
    for alias in self:
  File "/home/ubuntu/env/lib/python2.7/site-packages/django/db/utils.py", line 223, in __iter__
    return iter(self.databases)
  File "/home/ubuntu/env/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ubuntu/env/lib/python2.7/site-packages/django/db/utils.py", line 156, in databases
    self._databases = settings.DATABASES
  File "/home/ubuntu/env/lib/python2.7/site-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/home/ubuntu/env/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/ubuntu/env/lib/python2.7/site-packages/django/conf/__init__.py", line 116, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
```

can you please help me to sort out the problem.

Thanks in advance

**Comment by relekang** [comment]
Can you post your fabfile?

**Comment by mohammedasiftebla** [comment]
##fab file 

import os, subprocess


> from fabric.api import local, env
> from fabric.contrib import django
> from coverage import Coverage
>
> DEFAULT_RUN_ENV = 'dev'
> DEFAULT_TEST_ENV = 'regress'
> DEFAULT_PARALLEL = 10
> COVERAGE_OMITS = ["/testname/*", "*site-packages*", "*/fabfile*", "tests/*"]

>     'fab test:case=projname.test_s3' - to run all tests in projectname.test_s3 modules
>     'fab test:case=projectname.test_s3.TestS3.test_pre_signed_url' - to run specific test in projectname.test_s3 module'
Show quoted text
> def dumpdata(run_env=DEFAULT_TEST_ENV, app='projname', database='projdbname'):

>     """
>     Dump database to use as fixtures for regression test.
>     
>     """
>     # set django environment
>     _set_env_module(run_env)
>
>     # exclude options
>     exclude_opt = '--exclude'
>
>     # define exclude app or models
>     excludes = {'common': ['auth', 'contenttypes'],
>                 'projname': []}


>
>     fixture_dir_path = "%s/fixtures" % app
>     fixture_filename = "%s.json" % app
>
>     if not os.path.exists(fixture_dir_path):
>         os.makedirs(fixture_dir_path)
>
>     exclude_str = ""
>     for item in excludes:
>         if item == 'common' or item == database:
>             for ex in excludes[item]:
>                 exclude_str += " %s %s" % (exclude_opt, ex)
>
>     fixture_path = os.path.join(fixture_dir_path, fixture_filename)
>     local('python manage.py dumpdata -a %s %s --output %s' % (app, exclude_str, fixture_path))
>
>
> def shell(run_env=DEFAULT_RUN_ENV):
>     """
>     Start interact shell for Django
>     """
>
>     # set django environment
>     _set_env_module(run_env)
>
>     local('python manage.py shell')
>
>
> def manage(cmdstr, run_env=DEFAULT_RUN_ENV, debug=False):
>     """Call manage.py.  Ex:  fab manage:"runserver localhost:8080" """
>
>     # set django environment
>     _set_env_module(run_env)
>
>     if not debug:
>         local("python manage.py %s" % cmdstr)
>     else:
>         local("DEBUG_TRACE=1 python -m ipdb manage.py %s" % cmdstr)
>
>
> def _start_coverage():
>     print "Initiating code coverage analysis for main process (pid=%d)" % os.getpid()
>     # purge code coverage to ensure results in consistent state
>     # execute("/bin/rm -rf %s/* .coverage .coverage.*" % report_base)
>     cov = Coverage(branch=True, data_suffix=True, cover_pylib=False,
>                    omit=COVERAGE_OMITS, concurrency='multiprocessing')
>     cov.start()
>
>     return cov
>
>
> def _post_process_coverage(cov, report):
>     report_loc = "logs/coverage"
>
>     # stop coverage
>     cov.stop()
>     # cov.save()
>
>     # combine data files
>     cov.combine()
>     cov.save()
>
>     if report == 'html':
>         cov.html_report(directory=report_loc, omit=COVERAGE_OMITS)
>         print "HTML report stored in %s" % report_loc
>
>
> def _get_user_offset():
>     user = env.user
>
>     if user == "user6":
>         return 100
>     elif user == "user7":
>         return 200
>     elif user == "user1":
>         return 300
>     elif user == "user2":
>         return 400
>     elif user == "ssrtu":
>         return 500
>     elif user == "user4":
>         return 600
>     else:
>         sys.stderr.write("Unknown user: %s" % user)
>         sys.exit(1)

**Comment by mitulshah44** [comment]
```
import os, subprocess
from fabric.api import local, env
from fabric.contrib import django
from coverage import Coverage

DEFAULT_RUN_ENV = 'dev'
DEFAULT_TEST_ENV = 'regress'
DEFAULT_PARALLEL = 10
COVERAGE_OMITS = ["/mnc/*", "*site-packages*", "*/fabfile*", "tests/*"]

def _initialize(run_env=DEFAULT_RUN_ENV, port=None, regressdb=None):
    init_port = 9000

    # set port
    if port:
        env.runserver_port = port
    else:
        env.runserver_port = str(init_port + _get_user_offset())

    # set host
    env.runserver_host = subprocess.check_output("hostname", shell=True, universal_newlines=True).strip('\n')

    # set regress db os environment
    if regressdb:
        os.environ['REGRESS_DB'] = regressdb

    # set django environment
    _set_env_module(run_env)

def _set_env_module(run_env=DEFAULT_RUN_ENV):

    # set django environment
    django.settings_module('config.%s' % run_env)

def runserver(run_env=DEFAULT_RUN_ENV, port=None, regressdb=None):
    """ Run django server
    """

    _initialize(run_env, port, regressdb)
    local("python manage.py runserver %(runserver_host)s:%(runserver_port)s" % env)

def remove_pyc():
    """Remove .pyc file
    """
    local("find . -name \*.pyc -delete")

def test(case=None, run_env=DEFAULT_TEST_ENV, parallel=DEFAULT_PARALLEL, port=None, regressdb=None, coverage=True,
         report='html'):
    """ Run test cases
ychmnc
    'fab test' - to run all tests
    'fab test:case=myproject.test_s3' - to run all tests in myproject.test_s3 modules
    'fab test:case=myproject.test_s3.TestS3.test_pre_signed_url' - to run specific test in myproject.test_s3 module'
    """

    if not case:
        case = 'tests'
    else:
        case = 'tests.%s' % case

    _initialize(run_env, port, regressdb)
    test_cmd = "manage.py test %s --parallel=%s" % (case, parallel)

    if coverage:  # run test with coverage
        # run coverage
        #local("coverage run --branch --parallel-mode --source='.' %(test_cmd)s" % coverage_env)
        local("coverage run --branch --parallel-mode %s" % test_cmd)

        # combine coverage data
        local("coverage combine")

        # run html report generation
        if report == 'html':
            local("coverage html")
    else:  # run test without coverage
        local("python %s" % test_cmd)

def test_sequential():
    local("python manage.py test")

def dumpdata(run_env=DEFAULT_TEST_ENV, app='myproject', database='myproject'):
    """
    Dump database to use as fixtures for regression test.
    For now, database param is not used.
    """
    # set django environment
    _set_env_module(run_env)

    # exclude options
    exclude_opt = '--exclude'

    # define exclude app or models
    excludes = {'common': ['auth', 'contenttypes'],
                'myproject': []}

    fixture_dir_path = "%s/fixtures" % app
    fixture_filename = "%s.json" % app

    if not os.path.exists(fixture_dir_path):
        os.makedirs(fixture_dir_path)

    exclude_str = ""
    for item in excludes:
        if item == 'common' or item == database:
            for ex in excludes[item]:
                exclude_str += " %s %s" % (exclude_opt, ex)

    fixture_path = os.path.join(fixture_dir_path, fixture_filename)
    local('python manage.py dumpdata -a %s %s --output %s' % (app, exclude_str, fixture_path))

def shell(run_env=DEFAULT_RUN_ENV):
    """
    Start interact shell for Django
    """

    # set django environment
    _set_env_module(run_env)

    local('python manage.py shell')

def manage(cmdstr, run_env=DEFAULT_RUN_ENV, debug=False):
    """Call manage.py.  Ex:  fab manage:"runserver localhost:8080" """

    # set django environment
    _set_env_module(run_env)

    if not debug:
        local("python manage.py %s" % cmdstr)
    else:
        local("DEBUG_TRACE=1 python -m ipdb manage.py %s" % cmdstr)

def _start_coverage():
    print "Initiating code coverage analysis for main process (pid=%d)" % os.getpid()
    # purge code coverage to ensure results in consistent state
    # execute("/bin/rm -rf %s/* .coverage .coverage.*" % report_base)
    cov = Coverage(branch=True, data_suffix=True, cover_pylib=False,
                   omit=COVERAGE_OMITS, concurrency='multiprocessing')
    cov.start()

    return cov

def _post_process_coverage(cov, report):
    report_loc = "logs/coverage"

    # stop coverage
    cov.stop()
    # cov.save()

    # combine data files
    cov.combine()
    cov.save()

    if report == 'html':
        cov.html_report(directory=report_loc, omit=COVERAGE_OMITS)
        print "HTML report stored in %s" % report_loc

def _get_user_offset():
    user = env.user

    if user == "user6":
        return 100
   else:
        sys.stderr.write("Unknown user: %s" % user)
        sys.exit(1)
```

**Comment by mitulshah44** [comment]
I want to know how fab command is working with executable file, because in my case it is executable file. Is it possible or I should go without fabric module? pls suggest
